### ISSUE TITLE
[meta] logo

### ISSUE THREAD

**Issue by jonnymbgood** [pleaseops/www#15]

**Comment by jonnymbgood** [comment]
![Bubble1](https://user-images.githubusercontent.com/485900/56579989-c8cab500-658e-11e9-8e80-e5af07790734.png)
![Bubble2](https://user-images.githubusercontent.com/485900/56579994-cbc5a580-658e-11e9-807b-a97c5b94c2fc.png)
![Bubble3](https://user-images.githubusercontent.com/485900/56579998-cd8f6900-658e-11e9-9195-bea3e870f0b3.png)
![Bubble4](https://user-images.githubusercontent.com/485900/56580001-cf592c80-658e-11e9-8b48-c61af0e14583.png)

@thuey

**Comment by thuey** [comment]
Looking great! I'd like to see how they look with an outline, instead of filled grey, though. The second one is my favorite from a proportion standpoint.

**Comment by jonnymbgood** [comment]
![Line1](https://user-images.githubusercontent.com/485900/56692961-95784b00-66a0-11e9-8437-52891da1c9f4.png)
![Line2](https://user-images.githubusercontent.com/485900/56692966-97daa500-66a0-11e9-81b2-2379a36b6c4a.png)
![Line3](https://user-images.githubusercontent.com/485900/56692972-9ad59580-66a0-11e9-9aa1-f9047d316aeb.png)
![Line4](https://user-images.githubusercontent.com/485900/56692981-9c9f5900-66a0-11e9-8e6b-a4b4e84161e7.png)

**Comment by thuey** [comment]
I really like the first one. Thoughts?

**Comment by jonnymbgood** [comment]
I can go with that one for now. I'll probably take another stab at it later on. What format(s) do you need? svg and png?

**Comment by jonnymbgood** [comment]
I thinned the line just a wee bit to make it 1/2 the width of the slash.

![Logo](https://user-images.githubusercontent.com/485900/56770811-2cf99e80-6772-11e9-9783-4467543c0a66.png)

**Comment by jonnymbgood** [comment]
```
<svg width="128" height="128" fill="none" xmlns="http://www.w3.org/2000/svg"><path fill="#fff" d="M0 0h128v128H0z"/><path fill-rule="evenodd" clip-rule="evenodd" d="M54 17h21c23.748 0 43 19.252 43 43v8c0 23.748-19.252 43-43 43H11V60c0-23.748 19.252-43 43-43zM4 60c0-27.614 22.386-50 50-50h21c27.614 0 50 22.386 50 50v8c0 27.614-22.386 50-50 50H9a5 5 0 0 1-5-5V60zm84.15-30.537l-15.047.092-32.294 68.503 15.443-.094 31.898-68.5z" fill="#000"/></svg>
```

**Comment by thuey** [comment]
Looks good, thanks!

**Comment by jonnymbgood** [comment]
Done!
