### ISSUE TITLE
[www] three feature sections

### ISSUE THREAD

**Issue by thuey** [pleaseops/www#4]
### V1 With a focus on discoverability

**Screenshot**
`please login aws primary`

**Blurb**
It can be a nightmare managing access to all of the services your team uses, much less making sure they know how to get to them all. PleaseOps makes it safe and simple for your team to access your infrastructure. It generates federated login URLs for supported services, such as AWS, and provides a lookup directory for custom services, so you can get rid of all those outdated bookmarks.

### V2 With a focus on access control

**Screenshot**
`please grant user jsmith permission "login aws primary"`

**Blurb**
It can be a nightmare managing who has access to what across several services, not to mention onboarding and offboarding. With PleaseOps, you can avoid the problem of rotating credentials by never provisioning employee-specific credentials in the first place. Granting access to a new employee is as simple as `please grant user jsmith role developer`, and removing an employee is as simple as `please remove user jsmith`.

## Section 2: Manage Operations
**Screenshot**
`please deploy jenkins myapp`

**Blurb**
Instead of adding notification integrations to ensure everyone knows when the last deploy happened, kick off code deployments with a chat message that the rest of the team can see. PleaseOps makes it easy to manage your operations from a single, visible interface.

## Section 3: Triage Issues
**Screenshot**
`please check kubernetes prod-cluster`

**Blurb**
When something goes wrong, it's important to make sure everyone is on the same page. With PleaseOps, your team can collaboratively triage issues within the same chat conversation. No more chasing down the right screenshot or link to send; instead, you can pull relevant information into the conversation with a simple command.

**Comment by thuey** [comment]
I wonder if `please deploy` is the right word. Sometimes it's not a deploy, but a build. Maybe `please run` would be better?

**Comment by thuey** [comment]
@jonnymbgood Can you take a look?

**Comment by jonnymbgood** [comment]
Looks good!

What if we added a bit of V2 to V1 for Section 1. Maybe add this to the end?
> Granting access  is as simple as `please grant role developer permission "login aws primary"` and then `please grant user jsmith role developer`.

As to deploy I agree. Maybe `trigger`? `start`? Or maybe let `deploy` stand, and add `build` as an alias or another command? It would be nice to leave the semantic meaning.

**Comment by jonnymbgood** [comment]
For section 3 we could show 3 different checks: `please check k8s cluster`, `please check k8s cluster ns`, and then `please check service aws`

For section 2 we could have `please build jenkins myapp`, `please deploy jenkins myapp`, and `please check service myapp`

**Comment by jonnymbgood** [comment]
Also a generic thought. Rather than focusing in the bad things that could be, maybe focus on the wonderful experience that could be? Just a thought about the tone.

**Comment by thuey** [comment]
For showing multiple commands, that will make it difficult to show the commands and their output. Unless we do a carousel for each.

As for the tone, that's a good point. I guess it depends on our Target audience. I was imagining a startup with some underexperienced dev put in charge of Ops who might not even realize the problems they have and would need them pointed out in order to appreciate how things could be. But maybe that's the wrong audience or the wrong approach. Thoughts?

**Comment by jonnymbgood** [comment]
We could have multiple commands in the text but only show one in the screenshot. Thoughts?

As for the tone, as long as we stay away from "your current ops sucks and you don't know what you are doing" we should be fine. Just thinking we should think and stay positive in our messaging.

**Comment by thuey** [comment]
Ah, that makes sense. I'll try to find a way to incorporate them into the
text.

Yeah, that's true. Do you think it's too negative in any places yet?
